from django.db import models


class Product(models.Model):
    uid = models.CharField(max_length=200, null=False)
    store = models.CharField(max_length=200, null=False)  # StoreEnum
    title = models.CharField(max_length=200, null=False)
    url = models.CharField(max_length=200, null=False)
    category = models.CharField(max_length=200, null=False)  # CategoryEnum
    description = models.TextField(default=None, null=True)
    images: list[str] = models.JSONField(default=list, null=False)
    images_0 = models.CharField(max_length=200, default=None, null=True)
    images_1 = models.CharField(max_length=200, default=None, null=True)
    images_2 = models.CharField(max_length=200, default=None, null=True)
    images_3 = models.CharField(max_length=200, default=None, null=True)
    images_4 = models.CharField(max_length=200, default=None, null=True)
    images_5 = models.CharField(max_length=200, default=None, null=True)
    price = models.FloatField(null=False)
    properties_as_text = models.TextField(null=False)
    properties_as_dict = models.JSONField(null=True)
    properties_brand = models.CharField(max_length=200, default=None, null=True)
    properties_label = models.CharField(max_length=200, default=None, null=True)
    properties_country = models.CharField(max_length=200, default=None, null=True)
    properties_color = models.CharField(max_length=200, default=None, null=True)
    properties_material = models.CharField(max_length=200, default=None, null=True)
    properties_mass_raw = models.CharField(max_length=200, default=None, null=True)
    properties_mass_num = models.FloatField(default=None, null=True)
    properties_mass_unit = models.CharField(max_length=200, default=None, null=True)
    properties_volume_raw = models.CharField(max_length=200, default=None, null=True)
    properties_volume_num = models.FloatField(default=None, null=True)
    properties_volume_unit = models.CharField(max_length=200, default=None, null=True)
    properties_dimensions_raw = models.CharField(max_length=200, default=None, null=True)
    properties_dimensions_d_list = models.JSONField(null=True)
    properties_dimensions_d_list_0 = models.FloatField(default=None, null=True)
    properties_dimensions_d_list_1 = models.FloatField(default=None, null=True)
    properties_dimensions_d_list_2 = models.FloatField(default=None, null=True)
    properties_dimensions_d_list_3 = models.FloatField(default=None, null=True)
    properties_dimensions_d_list_4 = models.FloatField(default=None, null=True)
    properties_dimensions_d_list_5 = models.FloatField(default=None, null=True)
    properties_dimensions_all_units_parsed = models.BooleanField(default=None, null=True)
    properties_art_codes: list[str] = models.JSONField(default=list, null=False)
    properties_art_codes_0 = models.CharField(max_length=200, default=None, null=True)
    properties_art_codes_1 = models.CharField(max_length=200, default=None, null=True)
    properties_art_codes_2 = models.CharField(max_length=200, default=None, null=True)
    properties_art_codes_3 = models.CharField(max_length=200, default=None, null=True)
    properties_art_codes_4 = models.CharField(max_length=200, default=None, null=True)
    properties_art_codes_5 = models.CharField(max_length=200, default=None, null=True)
    properties_category_list_raw: list[str] = models.JSONField(default=list, null=False)
    properties_category_list_raw_0 = models.CharField(max_length=200, default=None, null=True)
    properties_category_list_raw_1 = models.CharField(max_length=200, default=None, null=True)
    properties_category_list_raw_2 = models.CharField(max_length=200, default=None, null=True)
    properties_category_list_raw_3 = models.CharField(max_length=200, default=None, null=True)
    properties_category_list_raw_4 = models.CharField(max_length=200, default=None, null=True)
    properties_category_list_raw_5 = models.CharField(max_length=200, default=None, null=True)


class Match(models.Model):
    product_1 = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_1')
    product_2 = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_2', default=None, null=True)
    insurance = models.FloatField(default=1.0)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)


class MatchLLM(models.Model):
    product_1 = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_1_llm')
    product_2 = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_2_llm', default=None, null=True)
    llm_map = models.BooleanField(null=True)
    llm_insurance = models.IntegerField(null=True)
    llm_raw = models.CharField(max_length=20, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
