# Generated by Django 5.1.2 on 2024-10-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mapper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="properties_as_text",
            field=models.TextField(),
        ),
    ]
