# Generated by Django 5.1.2 on 2024-11-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mapper", "0003_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="llm_insurance",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="llm_map",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="llm_raw",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="insurance",
            field=models.FloatField(default=1.0, null=True),
        ),
    ]
